import type { ProjectDetection } from './detect.js';

export interface GeneratedConfig {
  /** Filename to write, relative to the project root. */
  filename: string;
  /** Full file contents. */
  content: string;
}

/** Single-quote-safe embedding of a detected string value. */
function q(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

/**
 * Render a ready-to-use `selector-healer.config.cjs` from a detection result.
 *
 * `.cjs` is chosen deliberately: it loads in every project (ESM or CJS, with or
 * without a TypeScript loader) where a `.ts` config can silently fail to load.
 * Low-confidence fields are annotated with `TODO`, and the auth example reads
 * credentials from `process.env` — never hardcoded.
 *
 * @param detection - the result of {@link detectProjectConfig}
 * @returns the filename to write and its contents
 *
 * @example
 * const { filename, content } = renderConfigFile(detectProjectConfig(cwd));
 * writeFileSync(filename, content);
 */
export function renderConfigFile(detection: ProjectDetection): GeneratedConfig {
  const frameworkTodo =
    detection.frameworkConfidence === 'default'
      ? " // TODO: set to 'playwright' | 'cypress' | 'webdriverio' | 'testcafe'"
      : '';
  const baseUrlTodo = detection.baseUrlConfident ? '' : " // TODO: set your app's base URL";
  const testDirTodo = detection.testDirConfident ? '' : ' // TODO: point this at your test files';

  const content = `/**
 * Selector Healer configuration — generated by \`selector-healer init\`.
 * Review the values below; any field with a trailing note was inferred.
 * @type {import('@selector-healer/core').HealerConfig}
 */
module.exports = {
  framework: '${q(detection.framework)}',${frameworkTodo}
  testDir: '${q(detection.testDir)}',${testDirTodo}
  testGlob: '${q(detection.testGlob)}',
  baseUrl: '${q(detection.baseUrl)}',${baseUrlTodo}
  headless: true,
  timeout: 30_000,

  // Screens behind login (or that only appear after an interaction) need a
  // setup hook so Selector Healer can reach them. Uncomment and adapt.
  // SECURITY: never hardcode credentials — read them from environment variables.
  // pages: [
  //   {
  //     name: 'Dashboard (after login)',
  //     url: '/dashboard',
  //     setup: async (page) => {
  //       await page.goto(process.env.BASE_URL ?? '${q(detection.baseUrl)}');
  //       await page.getByLabel('Email').fill(process.env.TEST_USER ?? '');
  //       await page.getByLabel('Password').fill(process.env.TEST_PASS ?? '');
  //       await page.getByRole('button', { name: 'Log in' }).click();
  //       await page.waitForURL('**/dashboard');
  //     },
  //   },
  // ],
};
`;

  return { filename: 'selector-healer.config.cjs', content };
}
